### PR TITLE
Add `domino.createIncrementalHTMLParser` API

### PR DESCRIPTION
**Pull request by cscott**
As requested in https://gerrit.wikimedia.org/r/471358

### CODE REVIEW

**Comment by arlolra** [comment]
:+1:

**Comment by mdholloway** [comment]
LGTM 👍 

Here's how it's looking in mobileapps with this incorporated:

```
mUtil.createDocument = (html) => {
    const MAX_PARSING_MS_PER_TICK = 100;

    function _pauseAfter(ms) {
        const start = Date.now();
        return () => (Date.now() - start) >= ms;
    }

    function _processIncremental(parser) {
        return new P((res, rej) => setImmediate(() => {
            try {
                if (parser.process(_pauseAfter(MAX_PARSING_MS_PER_TICK))) {
                    res(_processIncremental(parser));
                } else {
                    res(parser.document());
                }
            } catch (e) {
                rej(e);
            }
        }));
    }

    return P.resolve(domino.createIncrementalHTMLParser())
    .then((parser) => {
        parser.end(html);
        return _processIncremental(parser);
    });
};
```

**Comment by cscott** [comment]
I think you can clean that up a bit.  `Promise.resolve().then(()=>{ ... })` is another way to say `setImmediate`, for instance.
```
mUtil.createDocument = (html) => {
    const MAX_PARSING_MS_PER_TICK = 100;

    function _pauseAfter(ms) {
        const start = Date.now();
        return () => (Date.now() - start) >= ms;
    }
    let oneStep = () => Promise.resolve().then( () => {
       if (parser.process(_pauseAfter(MAX_PARSING_MS_PER_TICK))) {
            return oneStep();
       } else {
            return parser.document();
       }
    }
    return oneStep();
};
```
If you were using `prfun` (and I think bluebird has something similar) you could also write:
```
let oneStep = Promise.method(() => {
       if (parser.process(_pauseAfter(MAX_PARSING_MS_PER_TICK))) {
            return oneStep();
       } else {
            return parser.document();
       }
});
```
Both accomplish the `yield` by chaining promises, and in both cases you don't need to use the raw Promise constructor or manually catch exceptions.

**Comment by mdholloway** [comment]
Interestingly, the behavior of `Promise.resolve.then()` seems to vary by implementation.  It appears that only native promises end up deferring to the next tick, equivalent to `setImmediate`.

Testing with your last example:

```
const tickId = require('tick-id');

mUtil.createDocument = P.async(function *(html) {
    const parser = domino.createIncrementalHTMLParser();
    const ticks = [];
    parser.end(html);
    while (parser.process(_pauseAfter(MAX_PARSING_MS_PER_TICK))) {
        ticks.push(tickId());
        yield P.resolve();
    }
    console.log(ticks);
    return parser.document();
});
```
Results in the following depending on the Promise implementation used for the `Promise.resolve()` yielded in the `while` loop:

prfun: `[ 773, 773, 773, 773, 773, 773, 773 ]`
bluebird: `[ 773, 773, 773, 773, 773, 773, 773, 773 ]`
native: `[ 774, 775, 776, 777, 778, 779, 780 ]`

I suppose I could use native Promises selectively where I want this effect, but it seems a bit gross, and would look like a mistake to someone not intimately familiar with what's going on.

**Comment by cscott** [comment]
Bluebird does not implement ES6-compliant promises.

**Pull request merged**
