### PR TITLE
Improve the performance of toASCIILowerCase

### PR DESCRIPTION
**Pull request by arlolra**
/cc @cscott

### CODE REVIEW

**Comment by cscott** [comment]
Is this really faster?  The mind boggles.  Regexps are usually a lot faster than char-by-char conversions, and we'd expect all-lowercase strings to be passed through unmodified (while in your patch they are rebuilt character-by-character even if there weren't any uppercase letters to begin with).

What about alternatives like:
```
function toASCIILowercase(s) {
  if (!/[A-Z]/.test(s)) return s;
  // whatever
}
```
and/or
```
function toASCIILowercase(s) {
  return s.replace(/[A-Z]/g, function(c) { return String.fromCharCode(c.charCodeAt(0) + 32); });
}
```
?

**Comment by arlolra** [comment]
> Is this really faster?

Anecdotally, it seems to be.

The way I tested was with, `node bin/parse --page Minneapolis --trace time < /dev/null > /dev/null` and looked at "dpLoader".

|  |  |
| - | - |
| Baseline  | ~470  |
| This patch  | ~425  |
| First suggestion above (w/ baseline) | ~420  |
| First suggestion above (w/ this patch) | ~415  |
| Second suggestion above | ~480 |

**Comment by arlolra** [comment]
Sounds good to me.

**Comment by cscott** [comment]
Some performance numbers.  Benchmark is dpLoader time on `[[User:Acer/Simple4]]`, measured with:
```
node  bin/parse.js --trace time --page "User:Acer/Simple4" --replay
```
Variant | Run 1 | Run 2 | Run 3 | Avg
----------|----------|---------|----------|-------------
both | 3547 | 3588 | 3550 | 3561
[avoid calling toASCIILowerCase](https://github.com/cscott/domino/commit/08ee77fcbff4dac58f20ad224f8763af23183a07) | 4055 | 3854 | 3862 | 3923
[speed up toASCIILowerCase](https://github.com/cscott/domino/commit/5573579bf54d1b1112429f6021fb3f297bbbbb5d) | 3472 | 3171 | 3685 | 3442
baseline | 3922 | 4004 | 4051 | 3992

The "avoid calling" patch seemed to help in other testing, though; perhaps dpLoader is just not exercising that code path.  I need to look into that further.

**Pull request closed without merging**
