### PR TITLE
Use `Object.create(null)` when using an object as a Map.

### PR DESCRIPTION
**Pull request by cscott**
This ensures that we don't see `hasOwnProperty` & etc as keys in the Map.

We will see `__proto__` as a key in the map with value `null`, but that's harmless in most cases (since we test for truthy map values).

### CODE REVIEW

**Comment by cscott** [comment]
@arlolra, @tstarling, @fgnass Could you take a look at this before I merge it, just as a sanity check?

**Comment by arlolra** [comment]
Since `Object.prototype` is no longer in the prototype chain, `__proto__` won't return `null`. You'd need to call `Object.getPrototypeOf` to get that. Well, assuming ES6.

 Otherwise, seems fine.

**Comment by cscott** [comment]
@arlolra oh, that's nice behavior from `__proto__`, cool.  Yay ES6 spec.  Verified it works that way in node 5.1.0 (at least).

I was mostly worried about using `x.hasOwnProperty(y)` after I removed the prototype for `x`.  But I couldn't find any instances of that.  In fact, the only instances of hasOwnProperty (outside the test fixtures) are:
```
lib/attributes.js:  if (!Object.hasOwnProperty(p, '_attributeChangeHandlers')) {
lib/cssparser.js:        if (Properties.hasOwnProperty(prop)){
lib/cssparser.js:               if (supplier.hasOwnProperty(prop)){
```
Of those, the first is clearly a bug (it's testing whether `p` is a property in `Object` and ignoring the second argument).  I'll take a look at the second two and probably change them to `Object.prototype.hasOwnProperty.call(x, y)` just to be safe.

**Comment by cscott** [comment]
Added 34ab4550cecc9a71d5a579badde7062b46357325 to fix the bug described in the comment above.

**Pull request merged**
